name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers publishing when a tag is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install setuptools wheel twine

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish package to PyPI
      run: |
        # Find the latest .whl and .tar.gz files in the dist/ directory
        latest_whl=$(ls -t dist/*.whl | head -n 1)
        latest_tar_gz=$(ls -t dist/*.tar.gz | head -n 1)
        
        # Upload the latest files to PyPI
        twine upload $latest_whl $latest_tar_gz -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
